# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "immutable-3.8.1" = {
      name = "immutable";
      packageName = "immutable";
      version = "3.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-3.8.1.tgz";
        sha1 = "200807f11ab0f72710ea485542de088075f68cd2";
      };
    };
    "react-15.5.4" = {
      name = "react";
      packageName = "react";
      version = "15.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-15.5.4.tgz";
        sha1 = "fa83eb01506ab237cdc1c8c3b1cea8de012bf047";
      };
    };
    "react-addons-pure-render-mixin-15.5.2" = {
      name = "react-addons-pure-render-mixin";
      packageName = "react-addons-pure-render-mixin";
      version = "15.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-addons-pure-render-mixin/-/react-addons-pure-render-mixin-15.5.2.tgz";
        sha1 = "ebb846aeb2fd771336c232822923108f87d5bff2";
      };
    };
    "react-addons-test-utils-15.5.1" = {
      name = "react-addons-test-utils";
      packageName = "react-addons-test-utils";
      version = "15.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-addons-test-utils/-/react-addons-test-utils-15.5.1.tgz";
        sha1 = "e0d258cda2a122ad0dff69f838260d0c3958f5f7";
      };
    };
    "react-dom-15.5.4" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "15.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-15.5.4.tgz";
        sha1 = "ba0c28786fd52ed7e4f2135fe0288d462aef93da";
      };
    };
    "react-redux-5.0.4" = {
      name = "react-redux";
      packageName = "react-redux";
      version = "5.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-redux/-/react-redux-5.0.4.tgz";
        sha1 = "1563babadcfb2672f57f9ceaa439fb16bf85d55b";
      };
    };
    "react-router-2.8.1" = {
      name = "react-router";
      packageName = "react-router";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-2.8.1.tgz";
        sha1 = "73e9491f6ceb316d0f779829081863e378ee4ed7";
      };
    };
    "redux-3.6.0" = {
      name = "redux";
      packageName = "redux";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux/-/redux-3.6.0.tgz";
        sha1 = "887c2b3d0b9bd86eca2be70571c27654c19e188d";
      };
    };
    "fbjs-0.8.12" = {
      name = "fbjs";
      packageName = "fbjs";
      version = "0.8.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/fbjs/-/fbjs-0.8.12.tgz";
        sha1 = "10b5d92f76d45575fd63a217d4ea02bea2f8ed04";
      };
    };
    "loose-envify-1.3.1" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.3.1.tgz";
        sha1 = "d1a8ad33fa9ce0e713d65fdd0ac8b748d478c848";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "prop-types-15.5.8" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.5.8.tgz";
        sha1 = "6b7b2e141083be38c8595aa51fc55775c7199394";
      };
    };
    "core-js-1.2.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz";
        sha1 = "652294c14651db28fa93bd2d5ff2983a4f08c636";
      };
    };
    "isomorphic-fetch-2.2.1" = {
      name = "isomorphic-fetch";
      packageName = "isomorphic-fetch";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-2.2.1.tgz";
        sha1 = "611ae1acf14f5e81f729507472819fe9733558a9";
      };
    };
    "promise-7.1.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.1.1.tgz";
        sha1 = "489654c692616b8aa55b0724fa809bb7db49c5bf";
      };
    };
    "setimmediate-1.0.5" = {
      name = "setimmediate";
      packageName = "setimmediate";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz";
        sha1 = "290cbb232e306942d7d7ea9b83732ab7856f8285";
      };
    };
    "ua-parser-js-0.7.12" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.12.tgz";
        sha1 = "04c81a99bdd5dc52263ea29d24c6bf8d4818a4bb";
      };
    };
    "node-fetch-1.6.3" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-1.6.3.tgz";
        sha1 = "dc234edd6489982d58e8f0db4f695029abcd8c04";
      };
    };
    "whatwg-fetch-2.0.3" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-2.0.3.tgz";
        sha1 = "9c84ec2dcf68187ff00bc64e1274b442176e1c84";
      };
    };
    "encoding-0.1.12" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.12.tgz";
        sha1 = "538b66f3ee62cd1ab51ec323829d1f9480c74beb";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "iconv-lite-0.4.16" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.16.tgz";
        sha1 = "65de3beeb39e2960d67f049f1634ffcbcde9014b";
      };
    };
    "asap-2.0.5" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.5.tgz";
        sha1 = "522765b50c3510490e52d7dcfe085ef9ba96958f";
      };
    };
    "js-tokens-3.0.1" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.1.tgz";
        sha1 = "08e9f132484a2c45a30907e9dc4d5567b7f114d7";
      };
    };
    "create-react-class-15.5.2" = {
      name = "create-react-class";
      packageName = "create-react-class";
      version = "15.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-react-class/-/create-react-class-15.5.2.tgz";
        sha1 = "6a8758348df660b88326a0e764d569f274aad681";
      };
    };
    "hoist-non-react-statics-1.2.0" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-1.2.0.tgz";
        sha1 = "aa448cf0986d55cc40773b17174b7dd066cb7cfb";
      };
    };
    "invariant-2.2.2" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.2.tgz";
        sha1 = "9e1f56ac0acdb6bf303306f338be3b204ae60360";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "lodash-es-4.17.4" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.4.tgz";
        sha1 = "dcc1d7552e150a0640073ba9cb31d70f032950e7";
      };
    };
    "history-2.1.2" = {
      name = "history";
      packageName = "history";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/history/-/history-2.1.2.tgz";
        sha1 = "4aa2de897a0e4867e4539843be6ecdb2986bfdec";
      };
    };
    "warning-3.0.0" = {
      name = "warning";
      packageName = "warning";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-3.0.0.tgz";
        sha1 = "32e5377cb572de4ab04753bdf8821c01ed605b7c";
      };
    };
    "deep-equal-1.0.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz";
        sha1 = "f5d260292b660e084eff4cdbc9f08ad3247448b5";
      };
    };
    "query-string-3.0.3" = {
      name = "query-string";
      packageName = "query-string";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-3.0.3.tgz";
        sha1 = "ae2e14b4d05071d4e9b9eb4873c35b0dcd42e638";
      };
    };
    "warning-2.1.0" = {
      name = "warning";
      packageName = "warning";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-2.1.0.tgz";
        sha1 = "21220d9c63afc77a8c92111e011af705ce0c6901";
      };
    };
    "strict-uri-encode-1.1.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-1.1.0.tgz";
        sha1 = "279b225df1d582b1f54e65addd4352e18faa0713";
      };
    };
    "symbol-observable-1.0.4" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.0.4.tgz";
        sha1 = "29bf615d4aa7121bdd898b22d4b3f9bc4e2aa03d";
      };
    };
  };
  args = {
    name = "biblio-client";
    packageName = "biblio-client";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."immutable-3.8.1"
      (sources."react-15.5.4" // {
        dependencies = [
          (sources."fbjs-0.8.12" // {
            dependencies = [
              sources."core-js-1.2.7"
              (sources."isomorphic-fetch-2.2.1" // {
                dependencies = [
                  (sources."node-fetch-1.6.3" // {
                    dependencies = [
                      (sources."encoding-0.1.12" // {
                        dependencies = [
                          sources."iconv-lite-0.4.16"
                        ];
                      })
                      sources."is-stream-1.1.0"
                    ];
                  })
                  sources."whatwg-fetch-2.0.3"
                ];
              })
              (sources."promise-7.1.1" // {
                dependencies = [
                  sources."asap-2.0.5"
                ];
              })
              sources."setimmediate-1.0.5"
              sources."ua-parser-js-0.7.12"
            ];
          })
          (sources."loose-envify-1.3.1" // {
            dependencies = [
              sources."js-tokens-3.0.1"
            ];
          })
          sources."object-assign-4.1.1"
          sources."prop-types-15.5.8"
        ];
      })
      (sources."react-addons-pure-render-mixin-15.5.2" // {
        dependencies = [
          (sources."fbjs-0.8.12" // {
            dependencies = [
              sources."core-js-1.2.7"
              (sources."isomorphic-fetch-2.2.1" // {
                dependencies = [
                  (sources."node-fetch-1.6.3" // {
                    dependencies = [
                      (sources."encoding-0.1.12" // {
                        dependencies = [
                          sources."iconv-lite-0.4.16"
                        ];
                      })
                      sources."is-stream-1.1.0"
                    ];
                  })
                  sources."whatwg-fetch-2.0.3"
                ];
              })
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.1"
                ];
              })
              (sources."promise-7.1.1" // {
                dependencies = [
                  sources."asap-2.0.5"
                ];
              })
              sources."setimmediate-1.0.5"
              sources."ua-parser-js-0.7.12"
            ];
          })
          sources."object-assign-4.1.1"
        ];
      })
      (sources."react-addons-test-utils-15.5.1" // {
        dependencies = [
          (sources."fbjs-0.8.12" // {
            dependencies = [
              sources."core-js-1.2.7"
              (sources."isomorphic-fetch-2.2.1" // {
                dependencies = [
                  (sources."node-fetch-1.6.3" // {
                    dependencies = [
                      (sources."encoding-0.1.12" // {
                        dependencies = [
                          sources."iconv-lite-0.4.16"
                        ];
                      })
                      sources."is-stream-1.1.0"
                    ];
                  })
                  sources."whatwg-fetch-2.0.3"
                ];
              })
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.1"
                ];
              })
              (sources."promise-7.1.1" // {
                dependencies = [
                  sources."asap-2.0.5"
                ];
              })
              sources."setimmediate-1.0.5"
              sources."ua-parser-js-0.7.12"
            ];
          })
          sources."object-assign-4.1.1"
        ];
      })
      (sources."react-dom-15.5.4" // {
        dependencies = [
          (sources."fbjs-0.8.12" // {
            dependencies = [
              sources."core-js-1.2.7"
              (sources."isomorphic-fetch-2.2.1" // {
                dependencies = [
                  (sources."node-fetch-1.6.3" // {
                    dependencies = [
                      (sources."encoding-0.1.12" // {
                        dependencies = [
                          sources."iconv-lite-0.4.16"
                        ];
                      })
                      sources."is-stream-1.1.0"
                    ];
                  })
                  sources."whatwg-fetch-2.0.3"
                ];
              })
              (sources."promise-7.1.1" // {
                dependencies = [
                  sources."asap-2.0.5"
                ];
              })
              sources."setimmediate-1.0.5"
              sources."ua-parser-js-0.7.12"
            ];
          })
          (sources."loose-envify-1.3.1" // {
            dependencies = [
              sources."js-tokens-3.0.1"
            ];
          })
          sources."object-assign-4.1.1"
          sources."prop-types-15.5.8"
        ];
      })
      (sources."react-redux-5.0.4" // {
        dependencies = [
          (sources."create-react-class-15.5.2" // {
            dependencies = [
              (sources."fbjs-0.8.12" // {
                dependencies = [
                  sources."core-js-1.2.7"
                  (sources."isomorphic-fetch-2.2.1" // {
                    dependencies = [
                      (sources."node-fetch-1.6.3" // {
                        dependencies = [
                          (sources."encoding-0.1.12" // {
                            dependencies = [
                              sources."iconv-lite-0.4.16"
                            ];
                          })
                          sources."is-stream-1.1.0"
                        ];
                      })
                      sources."whatwg-fetch-2.0.3"
                    ];
                  })
                  (sources."promise-7.1.1" // {
                    dependencies = [
                      sources."asap-2.0.5"
                    ];
                  })
                  sources."setimmediate-1.0.5"
                  sources."ua-parser-js-0.7.12"
                ];
              })
              sources."object-assign-4.1.1"
            ];
          })
          sources."hoist-non-react-statics-1.2.0"
          sources."invariant-2.2.2"
          sources."lodash-4.17.4"
          sources."lodash-es-4.17.4"
          (sources."loose-envify-1.3.1" // {
            dependencies = [
              sources."js-tokens-3.0.1"
            ];
          })
          (sources."prop-types-15.5.8" // {
            dependencies = [
              (sources."fbjs-0.8.12" // {
                dependencies = [
                  sources."core-js-1.2.7"
                  (sources."isomorphic-fetch-2.2.1" // {
                    dependencies = [
                      (sources."node-fetch-1.6.3" // {
                        dependencies = [
                          (sources."encoding-0.1.12" // {
                            dependencies = [
                              sources."iconv-lite-0.4.16"
                            ];
                          })
                          sources."is-stream-1.1.0"
                        ];
                      })
                      sources."whatwg-fetch-2.0.3"
                    ];
                  })
                  sources."object-assign-4.1.1"
                  (sources."promise-7.1.1" // {
                    dependencies = [
                      sources."asap-2.0.5"
                    ];
                  })
                  sources."setimmediate-1.0.5"
                  sources."ua-parser-js-0.7.12"
                ];
              })
            ];
          })
        ];
      })
      (sources."react-router-2.8.1" // {
        dependencies = [
          (sources."history-2.1.2" // {
            dependencies = [
              sources."deep-equal-1.0.1"
              (sources."query-string-3.0.3" // {
                dependencies = [
                  sources."strict-uri-encode-1.1.0"
                ];
              })
              sources."warning-2.1.0"
            ];
          })
          sources."hoist-non-react-statics-1.2.0"
          sources."invariant-2.2.2"
          sources."warning-3.0.0"
          (sources."loose-envify-1.3.1" // {
            dependencies = [
              sources."js-tokens-3.0.1"
            ];
          })
        ];
      })
      (sources."redux-3.6.0" // {
        dependencies = [
          sources."lodash-4.17.4"
          sources."lodash-es-4.17.4"
          (sources."loose-envify-1.3.1" // {
            dependencies = [
              sources."js-tokens-3.0.1"
            ];
          })
          sources."symbol-observable-1.0.4"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}